### ISSUE TITLE
Crash on Fabric server launch

### ISSUE THREAD

**Issue by Flamaghl** [illusivesoulworks/spectrelib#3]
Hello,

There were not updates and everything was working fine yesterday, but today my Fabric server started to crash everytime I try to launch it, pointing at spectrelib.
As a precision, i have not subscribed to spectrelib, the only mod from you that I play is Veimining (Fabric/Forge/Quilt)
(so Spectrelib is not in my mod folder, but somehow got in my \.fabric\processedMods folder - i guess for veinmining to work)

Below error part of the server log (and I attach full server log to ticket):

 [main/ERROR]: A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'spectrelib'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric.jar:0.11.2]
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'spectrelib'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:387) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:385) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.14.23.jar:?]
	... 4 more
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/loader/impl/entrypoint/EntrypointUtils
	at com.illusivesoulworks.spectrelib.SpectrePreLaunchFabricMod.onPreLaunch(SpectrePreLaunchFabricMod.java:33) ~[spectrelib-0.13.13+1.20.1-8bd44f426b4b2253.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.14.23.jar:?]
	... 4 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.loader.impl.entrypoint.EntrypointUtils
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.23.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at com.illusivesoulworks.spectrelib.SpectrePreLaunchFabricMod.onPreLaunch(SpectrePreLaunchFabricMod.java:33) ~[spectrelib-0.13.13+1.20.1-8bd44f426b4b2253.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.14.23.jar:?]
	... 4 more

Thanks for help !
[latest.log](https://github.com/illusivesoulworks/spectrelib/files/12818319/latest.log)

**Comment by Flamaghl** [comment]
Forgot to mention that I play on 1.20.1 :)

Here is crash report + log on client side too
[crash-2023-10-05_14.38.37-client.txt](https://github.com/illusivesoulworks/spectrelib/files/12818440/crash-2023-10-05_14.38.37-client.txt)
[latest.log](https://github.com/illusivesoulworks/spectrelib/files/12818446/latest.log)

**Comment by Flamaghl** [comment]
Last update : If I take out vein mining mod, the server + client launch normally : So I will also open this ticket on vein mining side :)

**Comment by Poopooracoocoo** [comment]
As a workaround, you can downgrade Fabric Loader to 0.14.22

**Comment by TheIllusiveC4** [comment]
Yeah, the 0.14.23 version of Fabric Loader is incompatible with the current versions of SpectreLib. As mentioned above, you can downgrade Fabric Loader to 0.14.22 or below as a workaround.

**Comment by nickelswitte** [comment]
I have the same problem as the OP, with 1.20.1 as well. Is there a proper solution yet?

**Comment by TheIllusiveC4** [comment]
The solution is to either downgrade to Fabric Loader 0.14.22 or wait until I update the mods that use this to the newer version. Some of the mods are already updated, and the others I'm still working on.

**Comment by TheIllusiveC4** [comment]
I've completed the updates on all of my mods, all of them should now work on Fabric Loader 0.14.23 and above. Thank you everyone for your patience and I apologize for any inconvenience. Please update all of your mods if you are still having issues and report back if that does not solve the problem.

In addition, in case there any other mods in the wild that are using this library and haven't updated yet, I've made releases on GitHub for the hotfix needed to run them:
https://github.com/illusivesoulworks/spectrelib/releases

There's one release each for 1.19-1.19.4 and 1.20-1.20.1. Simply grab the one for your version and mod loader (the regular jars, _not_ the sources ones) and install it, which will manually override any previous versions of the library installed.

**Comment by Cheesy-Brik** [comment]
This issue has resurfaced with me, launches fine client side. Can play worlds and everything, crashes when running a server.
1.20.1, fabric 1.15.10.

**Comment by Poopooracoocoo** [comment]
@Cheesy-Brik no log?

**Comment by TheIllusiveC4** [comment]
> This issue has resurfaced with me, launches fine client side. Can play worlds and everything, crashes when running a server.
1.20.1, fabric 1.15.10.

As mentioned in the other issue thread you created, your crash is for another reason and isn't due to this mod.
