### ISSUE TITLE
1.20.1 Fabric Server Crash

### ISSUE THREAD

**Issue by Cheesy-Brik** [illusivesoulworks/spectrelib#8]
Works fine on client side but causes a crash when running a server jar
This is really weird as I can play worlds fine on client
Why is there separate behavior for a server.jar???

Error
```
[20:40:32] [main/ERROR]: A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'spectrelib'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.10.jar:?]
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'spectrelib'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.15.10.jar:?]
	... 3 more
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'spectrelib' due to errors, provided by 'chargedcharms'!
	at com.illusivesoulworks.spectrelib.EntrypointUtils.lambda$invokeEntrypoints$0(EntrypointUtils.java:25) ~[spectrelib-0.13.15+1.20.1-7f355525f2546358.jar:?]
	at com.illusivesoulworks.spectrelib.EntrypointUtils.gatherExceptions(EntrypointUtils.java:41) ~[spectrelib-0.13.15+1.20.1-7f355525f2546358.jar:?]
	at com.illusivesoulworks.spectrelib.EntrypointUtils.invokeEntrypoints(EntrypointUtils.java:25) ~[spectrelib-0.13.15+1.20.1-7f355525f2546358.jar:?]
	at com.illusivesoulworks.spectrelib.SpectrePreLaunchFabricMod.onPreLaunch(SpectrePreLaunchFabricMod.java:32) ~[spectrelib-0.13.15+1.20.1-7f355525f2546358.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.15.10.jar:?]
	... 3 more
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_5321.method_29180(class_5321.java:35) ~[server-intermediary.jar:?]
	at net.minecraft.class_7924.method_47517(class_7924.java:200) ~[server-intermediary.jar:?]
	at net.minecraft.class_7924.<clinit>(class_7924.java:93) ~[server-intermediary.jar:?]
	at net.minecraft.class_8111.<clinit>(class_8111.java:10) ~[server-intermediary.jar:?]
	at chargedcharms.common.effect.AbsorptionEffectProvider.<clinit>(AbsorptionEffectProvider.java:17) ~[chargedcharms-1.20.1-2.0.0.5-FABRIC.jar:?]
	at chargedcharms.common.CharmEffectProviders.init(CharmEffectProviders.java:42) ~[chargedcharms-1.20.1-2.0.0.5-FABRIC.jar:?]
	at chargedcharms.ChargedCharms.init(ChargedCharms.java:25) ~[chargedcharms-1.20.1-2.0.0.5-FABRIC.jar:?]
	at chargedcharms.FabricConfigInitializer.onInitializeConfig(FabricConfigInitializer.java:11) ~[chargedcharms-1.20.1-2.0.0.5-FABRIC.jar:?]
	at com.illusivesoulworks.spectrelib.EntrypointUtils.invokeEntrypoints(EntrypointUtils.java:23) ~[spectrelib-0.13.15+1.20.1-7f355525f2546358.jar:?]
	at com.illusivesoulworks.spectrelib.SpectrePreLaunchFabricMod.onPreLaunch(SpectrePreLaunchFabricMod.java:32) ~[spectrelib-0.13.15+1.20.1-7f355525f2546358.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.15.10.jar:?]
	... 3 more
Caused by: java.lang.IllegalArgumentException: Not bootstrapped (called from registry ResourceKey[minecraft:root / minecraft:root])
	at net.minecraft.class_2966.method_36237(class_2966.java:123) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_36235(class_2966.java:116) ~[server-intermediary.jar:?]
	at net.minecraft.class_2370.<init>(class_2370.java:102) ~[server-intermediary.jar:?]
	at net.minecraft.class_2370.<init>(class_2370.java:98) ~[server-intermediary.jar:?]
	at net.minecraft.class_7923.<clinit>(class_7923.java:115) ~[server-intermediary.jar:?]
	at net.minecraft.class_5321.method_29180(class_5321.java:35) ~[server-intermediary.jar:?]
	at net.minecraft.class_7924.method_47517(class_7924.java:200) ~[server-intermediary.jar:?]
	at net.minecraft.class_7924.<clinit>(class_7924.java:93) ~[server-intermediary.jar:?]
	at net.minecraft.class_8111.<clinit>(class_8111.java:10) ~[server-intermediary.jar:?]
	at chargedcharms.common.effect.AbsorptionEffectProvider.<clinit>(AbsorptionEffectProvider.java:17) ~[chargedcharms-1.20.1-2.0.0.5-FABRIC.jar:?]
	at chargedcharms.common.CharmEffectProviders.init(CharmEffectProviders.java:42) ~[chargedcharms-1.20.1-2.0.0.5-FABRIC.jar:?]
	at chargedcharms.ChargedCharms.init(ChargedCharms.java:25) ~[chargedcharms-1.20.1-2.0.0.5-FABRIC.jar:?]
	at chargedcharms.FabricConfigInitializer.onInitializeConfig(FabricConfigInitializer.java:11) ~[chargedcharms-1.20.1-2.0.0.5-FABRIC.jar:?]
	at com.illusivesoulworks.spectrelib.EntrypointUtils.invokeEntrypoints(EntrypointUtils.java:23) ~[spectrelib-0.13.15+1.20.1-7f355525f2546358.jar:?]
	at com.illusivesoulworks.spectrelib.SpectrePreLaunchFabricMod.onPreLaunch(SpectrePreLaunchFabricMod.java:32) ~[spectrelib-0.13.15+1.20.1-7f355525f2546358.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.15.10.jar:?]
	... 3 more
```

**Comment by Cheesy-Brik** [comment]
Same fabric version and everything on client as well

**Comment by TheIllusiveC4** [comment]
I believe this is an issue from Charged Charms attempting to access some classes too early.
